<?php

/**
 * This is the model base class for the table "status".
 * DO NOT MODIFY THIS FILE! It is automatically generated by giix.
 * If any changes are necessary, you must set or override the required
 * property or method in class "Status".
 *
 * Columns in table "status" available as properties of the model,
 * followed by relations of table "status" available as properties of the model.
 *
 * @property integer $idSTATUS
 * @property string $acronym
 * @property string $title
 * @property string $description
 *
 * @property Authority[] $authorities
 * @property MailGroup[] $mailGroups
 * @property MailListGroup[] $mailListGroups
 * @property Requisition[] $requisitions
 * @property StatusGroupAccess[] $statusGroupAccesses
 */
abstract class BaseStatus extends GxActiveRecord {

	public static function model($className=__CLASS__) {
		return parent::model($className);
	}

	public function tableName() {
		return 'status';
	}

	public static function label($n = 1) {
		return Yii::t('app', 'Status|Statuses', $n);
	}

	public static function representingColumn() {
		return 'title';
	}

	public function rules() {
		return array(
			array('acronym, title', 'required'),
			array('acronym', 'length', 'max'=>2),
			array('title, description', 'length', 'max'=>45),
			array('description', 'default', 'setOnEmpty' => true, 'value' => null),
			array('idSTATUS, acronym, title, description', 'safe', 'on'=>'search'),
		);
	}

	public function relations() {
		return array(
			'authorities' => array(self::HAS_MANY, 'Authority', 'STATUS_idSTATUS'),
			'mailGroups' => array(self::HAS_MANY, 'MailGroup', 'STATUS_idSTATUS'),
			'mailListGroups' => array(self::HAS_MANY, 'MailListGroup', 'STATUS_idSTATUS'),
			'requisitions' => array(self::HAS_MANY, 'Requisition', 'STATUS_idSTATUS'),
			'statusGroupAccesses' => array(self::HAS_MANY, 'StatusGroupAccess', 'STATUS_idSTATUS'),
		);
	}

	public function pivotModels() {
		return array(
		);
	}

	public function attributeLabels() {
		return array(
			'idSTATUS' => Yii::t('app', 'Id Status'),
			'acronym' => Yii::t('app', 'Acronym'),
			'title' => Yii::t('app', 'Title'),
			'description' => Yii::t('app', 'Description'),
			'authorities' => null,
			'mailGroups' => null,
			'mailListGroups' => null,
			'requisitions' => null,
			'statusGroupAccesses' => null,
		);
	}

	public function search() {
		$criteria = new CDbCriteria;

		$criteria->compare('idSTATUS', $this->idSTATUS);
		$criteria->compare('acronym', $this->acronym, true);
		$criteria->compare('title', $this->title, true);
		$criteria->compare('description', $this->description, true);

		return new CActiveDataProvider($this, array(
			'criteria' => $criteria,
		));
	}
}