<?php

/**
 * This is the model base class for the table "reqtype".
 * DO NOT MODIFY THIS FILE! It is automatically generated by giix.
 * If any changes are necessary, you must set or override the required
 * property or method in class "ReqType".
 *
 * Columns in table "reqtype" available as properties of the model,
 * followed by relations of table "reqtype" available as properties of the model.
 *
 * @property integer $id
 * @property string $acronym
 * @property string $name
 *
 * @property Requisition[] $requisitions
 */
abstract class BaseReqType extends GxActiveRecord {

	public static function model($className=__CLASS__) {
		return parent::model($className);
	}

	public function tableName() {
		return 'reqtype';
	}

	public static function label($n = 1) {
		return Yii::t('app', 'ReqType|ReqTypes', $n);
	}

	public static function representingColumn() {
		return 'acronym';
	}

	public function rules() {
		return array(
			array('acronym, name', 'required'),
			array('acronym', 'length', 'max'=>3),
			array('name', 'length', 'max'=>100),
			array('id, acronym, name', 'safe', 'on'=>'search'),
		);
	}

	public function relations() {
		return array(
			'requisitions' => array(self::HAS_MANY, 'Requisition', 'REQTYPE_idREQTYPE'),
		);
	}

	public function pivotModels() {
		return array(
		);
	}

	public function attributeLabels() {
		return array(
			'id' => Yii::t('app', 'ID'),
			'acronym' => Yii::t('app', 'Acronym'),
			'name' => Yii::t('app', 'Name'),
			'requisitions' => null,
		);
	}

	public function search() {
		$criteria = new CDbCriteria;

		$criteria->compare('id', $this->id);
		$criteria->compare('acronym', $this->acronym, true);
		$criteria->compare('name', $this->name, true);

		return new CActiveDataProvider($this, array(
			'criteria' => $criteria,
		));
	}
}