<?php

/**
 * This is the model base class for the table "req_order".
 * DO NOT MODIFY THIS FILE! It is automatically generated by giix.
 * If any changes are necessary, you must set or override the required
 * property or method in class "ReqOrder".
 *
 * Columns in table "req_order" available as properties of the model,
 * followed by relations of table "req_order" available as properties of the model.
 *
 * @property integer $idREQ_ORDER
 * @property integer $REQUISITION_idREQUISITION
 * @property integer $po_num
 * @property string $date_order
 * @property string $date_ship
 * @property integer $REQ_DECISION_idREQ_DECISION
 * @property string $note
 *
 * @property Requisition $rEQUISITIONIdREQUISITION
 * @property ReqDecision $rEQDECISIONIdREQDECISION
 */
abstract class BaseReqOrder extends GxActiveRecord {

	public static function model($className=__CLASS__) {
		return parent::model($className);
	}

	public function tableName() {
		return 'req_order';
	}

	public static function label($n = 1) {
		return Yii::t('app', 'ReqOrder|ReqOrders', $n);
	}

	public static function representingColumn() {
		return 'date_order';
	}

	public function rules() {
		return array(
			array('REQUISITION_idREQUISITION, po_num, date_order, date_ship, REQ_DECISION_idREQ_DECISION', 'required'),
			array('REQUISITION_idREQUISITION, po_num, REQ_DECISION_idREQ_DECISION', 'numerical', 'integerOnly'=>true),
			array('note', 'length', 'max'=>500),
			array('note', 'default', 'setOnEmpty' => true, 'value' => null),
			array('idREQ_ORDER, REQUISITION_idREQUISITION, po_num, date_order, date_ship, REQ_DECISION_idREQ_DECISION, note', 'safe', 'on'=>'search'),
		);
	}

	public function relations() {
		return array(
			'rEQUISITIONIdREQUISITION' => array(self::BELONGS_TO, 'Requisition', 'REQUISITION_idREQUISITION'),
			'rEQDECISIONIdREQDECISION' => array(self::BELONGS_TO, 'ReqDecision', 'REQ_DECISION_idREQ_DECISION'),
		);
	}

	public function pivotModels() {
		return array(
		);
	}

	public function attributeLabels() {
		return array(
			'idREQ_ORDER' => Yii::t('app', 'Id Req Order'),
			'REQUISITION_idREQUISITION' => null,
			'po_num' => Yii::t('app', 'Po Num'),
			'date_order' => Yii::t('app', 'Date Order'),
			'date_ship' => Yii::t('app', 'Date Ship'),
			'REQ_DECISION_idREQ_DECISION' => null,
			'note' => Yii::t('app', 'Note'),
			'rEQUISITIONIdREQUISITION' => null,
			'rEQDECISIONIdREQDECISION' => null,
		);
	}

	public function search() {
		$criteria = new CDbCriteria;

		$criteria->compare('idREQ_ORDER', $this->idREQ_ORDER);
		$criteria->compare('REQUISITION_idREQUISITION', $this->REQUISITION_idREQUISITION);
		$criteria->compare('po_num', $this->po_num);
		$criteria->compare('date_order', $this->date_order, true);
		$criteria->compare('date_ship', $this->date_ship, true);
		$criteria->compare('REQ_DECISION_idREQ_DECISION', $this->REQ_DECISION_idREQ_DECISION);
		$criteria->compare('note', $this->note, true);

		return new CActiveDataProvider($this, array(
			'criteria' => $criteria,
		));
	}
}