<?php

/**
 * This is the model base class for the table "status_group_access".
 * DO NOT MODIFY THIS FILE! It is automatically generated by giix.
 * If any changes are necessary, you must set or override the required
 * property or method in class "StatusGroupAccess".
 *
 * Columns in table "status_group_access" available as properties of the model,
 * followed by relations of table "status_group_access" available as properties of the model.
 *
 * @property integer $idSTATUS_GROUP_ACCESS
 * @property integer $STATUS_idSTATUS
 * @property integer $GROUP_idGROUP
 *
 * @property Status $sTATUSIdSTATUS
 * @property Group $gROUPIdGROUP
 */
abstract class BaseStatusGroupAccess extends GxActiveRecord {

	public static function model($className=__CLASS__) {
		return parent::model($className);
	}

	public function tableName() {
		return 'status_group_access';
	}

	public static function label($n = 1) {
		return Yii::t('app', 'Group Sign Access|Group Sign Access', $n);
	}

	public static function representingColumn() {
		return 'idSTATUS_GROUP_ACCESS';
	}

	public function rules() {
		return array(
			array('STATUS_idSTATUS, GROUP_idGROUP', 'required'),
			array('STATUS_idSTATUS, GROUP_idGROUP', 'numerical', 'integerOnly'=>true),
			array('idSTATUS_GROUP_ACCESS, STATUS_idSTATUS, GROUP_idGROUP', 'safe', 'on'=>'search'),
		);
	}

	public function relations() {
		return array(
			'sTATUSIdSTATUS' => array(self::BELONGS_TO, 'Status', 'STATUS_idSTATUS'),
			'gROUPIdGROUP' => array(self::BELONGS_TO, 'Group', 'GROUP_idGROUP'),
		);
	}

	public function pivotModels() {
		return array(
		);
	}

	public function attributeLabels() {
		return array(
			'idSTATUS_GROUP_ACCESS' => Yii::t('app', 'ID'),
			'STATUS_idSTATUS' => Yii::t('app', 'When Status is...'),
			'GROUP_idGROUP' => Yii::t('app', 'Grant Sign Access to Group...'),
			'sTATUSIdSTATUS' => null,
			'gROUPIdGROUP' => null,
		);
	}

	public function search() {
		$criteria = new CDbCriteria;

		$criteria->compare('idSTATUS_GROUP_ACCESS', $this->idSTATUS_GROUP_ACCESS);
		$criteria->compare('STATUS_idSTATUS', $this->STATUS_idSTATUS);
		$criteria->compare('GROUP_idGROUP', $this->GROUP_idGROUP);

		return new CActiveDataProvider($this, array(
			'criteria' => $criteria,
		));
	}
}