<?php

/**
 * This is the model base class for the table "group".
 * DO NOT MODIFY THIS FILE! It is automatically generated by giix.
 * If any changes are necessary, you must set or override the required
 * property or method in class "Group".
 *
 * Columns in table "group" available as properties of the model,
 * followed by relations of table "group" available as properties of the model.
 *
 * @property integer $idGROUP
 * @property string $title
 * @property string $description
 *
 * @property Authority[] $authorities
 * @property MailListGroup[] $mailListGroups
 * @property StatusGroupAccess[] $statusGroupAccesses
 * @property User[] $users
 */
abstract class BaseGroup extends GxActiveRecord {

	public static function model($className=__CLASS__) {
		return parent::model($className);
	}

	public function tableName() {
		return 'group';
	}

	public static function label($n = 1) {
		return Yii::t('app', 'Group|Groups', $n);
	}

	public static function representingColumn() {
		return 'description';
	}

	public function rules() {
		return array(
			array('title', 'required'),
			array('title, description', 'length', 'max'=>45),
			array('description', 'default', 'setOnEmpty' => true, 'value' => null),
			array('idGROUP, title, description', 'safe', 'on'=>'search'),
		);
	}

	public function relations() {
		return array(
			'authorities' => array(self::HAS_MANY, 'Authority', 'GROUP_idGROUP'),
			'mailListGroups' => array(self::HAS_MANY, 'MailListGroup', 'GROUP_idGROUP'),
			'statusGroupAccesses' => array(self::HAS_MANY, 'StatusGroupAccess', 'GROUP_idGROUP'),
			'users' => array(self::HAS_MANY, 'User', 'GROUP_idGROUP'),
		);
	}

	public function pivotModels() {
		return array(
		);
	}

	public function attributeLabels() {
		return array(
			'idGROUP' => Yii::t('app', 'Id Group'),
			'title' => Yii::t('app', 'Title'),
			'description' => Yii::t('app', 'Description'),
			'authorities' => null,
			'mailListGroups' => null,
			'statusGroupAccesses' => null,
			'users' => null,
		);
	}

	public function search() {
		$criteria = new CDbCriteria;

		$criteria->compare('idGROUP', $this->idGROUP);
		$criteria->compare('title', $this->title, true);
		$criteria->compare('description', $this->description, true);

		return new CActiveDataProvider($this, array(
			'criteria' => $criteria,
		));
	}
}